server:
  port: 40002

spring:
  application:
    name: gateway-service

  cloud:
    config:
      enabled: false

    gateway:

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user-service/members/loginId, /user-service/members/loginId/duplicate, /user-service/members/password, /user-service/admin/login
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/members/{memberId}
            - Method=GET, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: token.secret
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/admin/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: admin.secret
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}


        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/products/{productId}/favorite, /product-service/products/{productId}/inquires, /product-service/products/inquires/{inquireId}
            - Method=POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: token.secret
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
            - Method=POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: admin.secret
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}


        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/coupon, /order-service/coupon/{couponId}
            - Method=POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: admin.secret
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - name: AuthenticationHeaderFilter
              args:
                propertyKey: token.secret
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}


      default-filters:
        - name: GlobalFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: local_secret_test_token_123456789123456789123456789123456789

admin:
  secret: admin_secret_test_token_123456789123456789123456789123456789