spring:
  application:
    name: order-service

server:
  port: 8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.30.1.24:8761/eureka