spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:http://121.134.166.240:40001/"
  cloud:
    config:
      name: ecommerce
      profile: prod

server:
  port: 8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://121.134.166.240:8761/eureka
